sudo: required
dist: xenial
language: go
go:
    - 1.14.x

matrix:
    include:
        - os: osx
          install:
              - go get -d -t -v ./...
              - go test -v ./src/...
              - go build -v -o groot ./main.go
          script:
              - cd testing
              - sh run_travis_tests.sh
        - os: linux
          install:
              - go get -d -t -v ./...
              - go test -v ./src/...
              - go build -v -o groot ./main.go
          script:
              - cd testing
              - sh run_travis_tests.sh
